### ISSUE TITLE
前段部署完毕后出现登陆 Failed to fetch 以及TG BOT发消息无反馈

### ISSUE THREAD

**Issue by enweny** [wzs8/buling-imgbed#1]
根据教程一步一步来
出现2个问题
TG BOT创建成功后，通过@TG BOT给TG BOT发消息，无任何反馈消息
然后继续部署前端，部署成功并可以通过域名访问到，但登陆输入admin出现Failed to fetch

**Comment by wzs8** [comment]
经测试，后端的网址不能开cf的防火墙。
