### ISSUE TITLE
后端部署后能通过Tg上传到R2，但是访问显示Not Found 

### ISSUE THREAD

**Issue by liqiujiong** [wzs8/buling-imgbed#5]
按后端教程部署的，会是哪里出现问题呢？
<img width="753" alt="image" src="https://github.com/user-attachments/assets/f4b4d1ac-0305-4f38-83c1-b4d8ec23860b">

<img width="1001" alt="image" src="https://github.com/user-attachments/assets/250ba13b-ef10-433b-b2ba-bb51ba702862">
文件已经上传到了R2
<img width="1324" alt="image" src="https://github.com/user-attachments/assets/6c1d76bd-8f82-4048-afcc-d24d3bc819f3">

**Comment by wzs8** [comment]
R2存储桶需要单独设置域名，网站后台绑定的是R2存储桶域名不是workers域名。

**Comment by liqiujiong** [comment]
已解决。 添加了R2自定义域名，修改D1 SQL里面的域名就可以了
